matrix:
 include:
  - os: linux
    language: python
    python: 3.5
  - os: linux
    language: python
    python: 3.6
  - os: osx
    language: generic
    before_install:
    - mkdir -p /Users/travis/.matplotlib
    - "echo 'backend: TkAgg' > /Users/travis/.matplotlib/matplotlibrc"
    - brew update
    - brew upgrade python
    - pip3 install virtualenv
    - virtualenv py3env -p python3
    - source py3env/bin/activate

cache: pip

install:
  - pip install numpy
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - ipcluster start -n 2 --daemon
  #- travis_wait 20 make test
  - make test
